In [ ]:

import numpy as np

np.genfromtxt('/content/drive/MyDrive/Dataset/nyc_taxis.csv', delimiter=None)

data = np.genfromtxt('/content/drive/MyDrive/Dataset/nyc_taxis.csv', delimiter=',')

print(data.shape)

(2014, 15)


In [ ]:
import numpy as np
taxi = np.genfromtxt('/content/drive/MyDrive/Dataset/nyc_taxis.csv', delimiter=',')
taxi_shape = taxi.shape
print(taxi_shape)

(2014, 15)


Why are we recieving NAN values when converting the data in our CSV to a ndarray

In [ ]:
print(taxi[0])

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]


We can see by checking the type that values are already converted to float (numpy checks what the values are in the file so doing a conversion like when using a list of lists, is not necessary)

In [ ]:
print(taxi.dtype)

float64


the reason the first row has NAN values is because this is the header row and contains the index/column names which are not numerical / float values. NAN stands for Not a Number.

In [ ]:
print(taxi[1:2,1:4])

[[1. 1. 5.]]


In [ ]:
taxi = taxi[1:]
print(taxi[0:1])

[[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
  2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
  1.000e+00]]


Two different methods in Numpy to remove the header row

Best practice is to handle header row while loading in the data rather than after

In [ ]:
taxi = np.genfromtxt('/content/drive/MyDrive/Dataset/nyc_taxis.csv', delimiter=',')
taxi_header_removed = taxi[1:]
removed_shape = taxi_header_removed.shape

taxi_header_skipped = np.genfromtxt('/content/drive/MyDrive/Dataset/nyc_taxis.csv', delimiter=',', skip_header=1)
skipped_shape = taxi_header_skipped.shape

print(taxi_header_removed[:5])
print(taxi_header_skipped[:5])

print("\nShape of taxi_header_removed:", removed_shape)
print("Shape of taxi_header_shipped:", skipped_shape)

[[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
  2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 1.000e+00
  1.629e+01 1.520e+03 4.500e+01 1.300e+00 0.000e+00 8.000e+00 5.430e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  1.270e+01 1.462e+03 3.650e+01 1.300e+00 0.000e+00 0.000e+00 3.780e+01
  2.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  8.700e+00 1.210e+03 2.600e+01 1.300e+00 0.000e+00 5.460e+00 3.276e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  5.560e+00 7.590e+02 1.750e+01 1.300e+00 0.000e+00 0.000e+00 1.880e+01
  2.000e+00]]
[[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
  2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000

Using NP array functionality to run a few different mathematical operations on an an array

In [ ]:
print(np.array([2, 4, 6, 8]) * 10)

[20 40 60 80]


In [ ]:
print(np.array([2, 4, 6, 8]) / 10)

[0.2 0.4 0.6 0.8]


In [ ]:
print(np.array([2, 4, 6, 8]) + 10)

[12 14 16 18]


In [ ]:
print(np.array([2, 4, 6, 8]) - 10)

[-8 -6 -4 -2]


Using a Boolean operation between an ndarray and a single value allows us to quickly identify which values in 

In [ ]:
print(np.array([2, 4, 6, 8]) < 5)

[ True  True False False]


In [ ]:
print(np.array([2, 4, 6, 8]) > 5)

[False False  True  True]


In [ ]:
a_bool = (np.array([2, 4, 6, 8]) < 3)
b_bool = (np.array([2, 4, 6, 8]) == "blue")
c_bool = (np.array([2, 4, 6, 8]) > 100)

<ipython-input-28-e38062bfec6c>:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  b_bool = (np.array([2, 4, 6, 8]) == "blue")


Some different examples of Boolean operations we can run on arrays.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])


a_bool = a < 3
b_bool = b == "blue"
c_bool = c > 100

Boolean Indexing
We have our array, we have our condition ( > 100) and then we assign the output of indexing for those conditions c[c_bool] to a variable called result

In [ ]:
c = np.array([80.0, 103.4, 96.9, 200.3])
c_bool = c > 100
result = c[c_bool]
print(result)

[103.4 200.3]


Using our taxi data set - we set the column we want to find data from in this case pickup_month (jan = 1, dec = 12); we then set our condition (or argument) we want only results in which the pickup_month is equivallent to 1 (january) we can then see there are 800 rides in the data set that took place in January by using len or shape.

In [ ]:
pickup_month = taxi[:, 1]
january_bool = pickup_month == 1
result = pickup_month[january_bool]
print(len(result))
print(result.shape)

800
(800,)


In [ ]:
january_rides = result.shape[0]
print(january_rides)

800


In [ ]:
pickup_month = taxi[:, 1]
february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0] 
print(february_rides)

176


Boolean Indexing with 2D ndarrys

In [ ]:
arr = np.array([
                [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]
               ])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
bool_1 = [True, True,
          True, True]
print(arr[bool_1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
bool_1 = [True, True,
          False, False]
print(arr[bool_1])

[[1 2 3]
 [4 5 6]]


In [ ]:
bool_2 = [False, True, True]
print(arr[:,bool_2])

[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


In [ ]:
bool_2 = [False, True, False]
print(arr[:,bool_2])

[[ 2]
 [ 5]
 [ 8]
 [11]]


Calculate taxi average speed using taxi data set

In [ ]:
trip_mph = taxi[:, 7] / (taxi[:, 8] / 3600)
print(trip_mph)

[        nan 37.11340206 38.58157895 ... 22.29907867 42.41551247
 36.90473407]


In [ ]:
trip_mph_bool = trip_mph > 20000
trips_over_20000_mph = taxi[trip_mph_bool, 5:9]
print(trips_over_20000_mph)

[[ 2.   2.  23.   1. ]
 [ 2.   2.  19.6  1. ]
 [ 2.   2.  16.7  2. ]
 [ 3.   3.  17.8  2. ]
 [ 2.   2.  17.2  2. ]
 [ 3.   3.  16.9  3. ]
 [ 2.   2.  27.1  4. ]]


As related to Taxi Dataset: Here's some info on selected columns:
📅 pickup_year: Trip's year 📅 pickup_month: Trip's month (January is 1, December is 12) 📅 pickup_day: Trip's day of the month 📍 pickup_location_code: Starting airport or borough 📍 dropoff_location_code: Ending airport or borough 📏 trip_distance: Trip distance in miles ⏱️ trip_length: Trip length in seconds 💵 fare_amount: Base fare in dollars 💰 total_amount: Total amount charged, including all fees, tolls, and tips
NYC Taxi Trip Data

Source: NYC Taxi and Limousine Commission
This data set includes a 1/50th random sample of all trips between January and June 2016 that either start or end at an aiport location.
Column Summary
pickup_year - The year of the trip.
pickup_month - The month of the trip (January is 1, December is 12).
pickup_day - The day of the month of the trip.
pickup_dayofweek - The day of the week (Monday is 1, Sunday is 7)
pickup_time - The time that the trip started, as one of six categories:
0 - 0:00am-3:59am.
1 - 4:00am-7:59am.
2 - 8:00am-11:59am.
3 - 12:00pm-3:59pm.
4 - 4:00pm-7:59pm.
5 - 8:00pm-11:59pm.
pickup_location_code - The airport or borough where the the trip started, as one of eight categories:
0 - Bronx.
1 - Brooklyn.
2 - JFK Airport.
3 - LaGuardia Airport.
4 - Manhattan.
5 - Newark Airport.
6 - Queens.
7 - Staten Island.
dropoff_location_code - The airport or borough where the the trip finished, using the same eight category codes as pickup_location_code.
trip_distance - The distance of the trip in miles.
trip_length - The length of the trip in seconds.
fare_amount - The base fare of the trip, in dollars.
fees_amount - Any fees added to the fare, eg surcharges, extras, and MTA taxes.
tolls_amount - The amount of all tolls paid during the trip.
tip_amount - The tip added by the customer - does not include cash tips.
total_amount - The total amount charged to the passenger, excluding cash tips.
payment_type - The payment type, one of six categories:
1 - Credit card.
2 - Cash.
3 - No charge.
4 - Dispute.
5 - Unknown.
6 - Voided trip.

In [ ]:
trip_mph_bool = trip_mph > 20000
trips_over_20000_mph = taxi[trip_mph_bool, 5:9]
print(trips_over_20000_mph)




SyntaxError: ignored

We are determing tip amounts greater than 20 (tip amounts is index 12) and returning index 5 through 13 for tip amounts greater than 20

In [ ]:
tip_amount = taxi[:, 12]
tip_bool = tip_amount > 20
top_tips = taxi[tip_bool, 5:14]
print(top_tips)


Assigning or changing values in ndarray

In [ ]:
a = np.array(['red', 'blue', 'black', 'blue', 'purple'])
a[0] = 'orange'
print(a)

['orange' 'blue' 'black' 'blue' 'purple']


Changing multiple values at once

In [ ]:
a[3:] = 'pink'
print(a)

['orange' 'blue' 'black' 'pink' 'pink']


Changing a specific index location value (in this case - row 1 index 2)

In [ ]:
ones = np.array([[1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1]])
ones[1, 2] = 99
print(ones)

[[ 1  1  1  1  1]
 [ 1  1 99  1  1]
 [ 1  1  1  1  1]]


An entire row

In [ ]:
ones[0] = 42
print(ones)

[[42 42 42 42 42]
 [ 1  1  0  1  1]
 [ 1  1  0  1  1]]


An entire index / column

In [ ]:
ones[:,2] = 0
print(ones)

[[42 42  0 42 42]
 [ 1  1  0  1  1]
 [ 1  1  0  1  1]]


In [ ]:
taxi_copy = taxi.copy()

Updating value

In [ ]:
taxi_copy[1066, 5] = 1


Updating multiple values

In [ ]:
taxi_copy[:,0] = 16

Assigning the mean value for two rows (550 and 551) with incorrect data
We are assigning the mean for the overall column that those two rows are in

In [ ]:
taxi_copy[550:552, 7] = taxi_copy[:,7].mean()
print(taxi_copy)

[[16.     nan   nan ...   nan   nan   nan]
 [16.    1.    1.   ... 11.65 69.99  1.  ]
 [16.    1.    1.   ...  8.   54.3   1.  ]
 ...
 [16.    6.   30.   ...  5.   63.34  1.  ]
 [16.    6.   30.   ...  8.95 44.75  1.  ]
 [16.    6.   30.   ...  0.   54.84  2.  ]]


Assignment using Boolean Arrays
a2_bool acts like a filter
We take our array (a2) and then use our filter [a2_bool] = to assign a value to anything in the array that meets that condition (> )

In [ ]:
a2 = np.array([1, 2, 3, 4, 5])
a2_bool = a2 > 2
a2[a2_bool] = 99
print(a2)

[ 1  2 99 99 99]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
a[a > 2] = 99
print(a)

[ 1  2 99 99 99]


In [ ]:
taxi_copy = taxi.copy()

Using taxi data set we are taking our trip_length column (index 8) and looking for values that are less than 60 (this is in seconds so under a minute) we are assigning anything under a minute a value of 0

In [ ]:
trip_length = taxi_copy[:,8]
trip_length_bool = trip_length < 60
trip_length[trip_length_bool] = 0


Assignment using Boolean Arrays Continued

In [ ]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b[b > 4] = 99
print(b)

[[ 1  2  3]
 [ 4 99 99]
 [99 99 99]]


In [ ]:
c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


after we specify that we want all rows for column index 1 that have a value greater than 2 - we specify the index location we want our new values assigned to otherwise it will overwrite every value in the array greater than 2 " c[c[:, 1] > 2] = 99"  now with this  c[c[:, 1] > 2, 1] = 99 (we are only including values in index 1 greater than 2 to overwrite)

In [ ]:
 c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
 c[c[:, 1] > 2, 1] = 99
 print(c)

[[ 1  2  3]
 [ 4 99  6]
 [ 7 99  9]]


In [ ]:
dropoff_location_code = taxi_copy[:, 6]
dropoff_location_code_jfk = dropoff_location_code = 2
drop_location_code[dropoff_location_code_jfk] ,

NameError: ignored

In [ ]:
# create a new array filled with `0`
zeros = np.zeros([taxi.shape[0], 1])
# append the array to the taxi data to create a new column
taxi_modified = np.concatenate([taxi, zeros], axis=1)
# inspect the last five columns of the first ten rows
print(taxi_modified[:10, -5:])


[[   nan    nan    nan    nan   0.  ]
 [  5.54  11.65  69.99   1.     0.  ]
 [  0.     8.    54.3    1.     0.  ]
 [  0.     0.    37.8    2.     0.  ]
 [  0.     5.46  32.76   1.     0.  ]
 [  0.     0.    18.8    2.     0.  ]
 [  0.    52.8  105.6    1.     0.  ]
 [  0.     6.45  32.25   1.     0.  ]
 [  0.     0.    22.8    2.     0.  ]
 [ 11.08  10.   131.38   1.     0.  ]]


In [ ]:
taxi_modified[taxi_modified[:, 6] == 2, 15] = 1
taxi_modified[taxi_modified[:, 6] == 3, 15] = 1
taxi_modified[taxi_modified[:, 6] == 5, 15] = 1

In [ ]:
print(taxi_modified[:10, -6:])


[[   nan    nan    nan    nan    nan   0.  ]
 [  0.8    5.54  11.65  69.99   1.     0.  ]
 [  1.3    0.     8.    54.3    1.     0.  ]
 [  1.3    0.     0.    37.8    2.     0.  ]
 [  1.3    0.     5.46  32.76   1.     0.  ]
 [  1.3    0.     0.    18.8    2.     0.  ]
 [  0.8    0.    52.8  105.6    1.     1.  ]
 [  1.3    0.     6.45  32.25   1.     0.  ]
 [  1.3    0.     0.    22.8    2.     0.  ]
 [  0.8   11.08  10.   131.38   1.     1.  ]]


In [ ]:
zeros = np.zeros([taxi.shape[0], 1])
print(zeros)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


If column 6 (taxi airport code column) is equivalent to 2, 3, or 5 column 15 (newly created column at the end of the columns in taxi is appending with the value 1 

In [ ]:
# create a new array filled with `0`
zeros = np.zeros([taxi.shape[0], 1])
# append the array to the taxi data to create a new column
taxi_modified = np.concatenate([taxi, zeros], axis=1)
# inspect the last five columns of the first ten rows
print(taxi_modified[:10, -5:])


taxi_modified[taxi_modified[:, 6] == 2, 15] = 1
taxi_modified[taxi_modified[:, 6] == 3, 15] = 1
taxi_modified[taxi_modified[:, 6] == 5, 15] = 1

[[   nan    nan    nan    nan   0.  ]
 [  5.54  11.65  69.99   1.     0.  ]
 [  0.     8.    54.3    1.     0.  ]
 [  0.     0.    37.8    2.     0.  ]
 [  0.     5.46  32.76   1.     0.  ]
 [  0.     0.    18.8    2.     0.  ]
 [  0.    52.8  105.6    1.     0.  ]
 [  0.     6.45  32.25   1.     0.  ]
 [  0.     0.    22.8    2.     0.  ]
 [ 11.08  10.   131.38   1.     0.  ]]


We know JFK airport code is 2 and contained in index 5 we are now assigning to variable JFK anything that in column 5 that has airport code 2
Based on taxi dataset, La Guardia is the busiest airport

In [ ]:
jfk = taxi[taxi[:,5] == 2]
jfk_count = jfk.shape[0]

laguardia = taxi[taxi[:,5] == 3]
laguardia_count = laguardia.shape[0]

newark = taxi[taxi[:,5] == 5]
newark_count = newark.shape[0]

print(jfk_count)
print(laguardia_count)
print(newark_count)

724
755
0


We are cleaning our taxi data set by only including trips that have an average trip mph or less than 100. 

In [ ]:
trip_distance = taxi[:, 7] # trip distance in miles
trip_length = taxi[:, 8] / 3600 # trip length in hours
trip_mph = trip_distance / trip_length # average trip speed in mph

cleaned_taxi = taxi[trip_mph < 100]

This is the value from the uncleaned data set

In [ ]:
mean_distance = taxi[1:,7].mean()
print(mean_distance)

12.924778936910084


We are now calculating the mean values of our cleaned data set

In [ ]:
mean_distance = cleaned_taxi[:,7].mean()
print(mean_distance)

12.902684630738525


Value from uncleaned data set

In [ ]:
mean_length = taxi[1:,8].mean()
print(mean_length)

2261.595131644312


Cleaned data set

In [ ]:
mean_length = cleaned_taxi[:,8].mean()
print(mean_length)

2271.691117764471


Unclean data set

In [ ]:
mean_total_amount = taxi[1:,13].mean()
print(mean_total_amount)

48.67809239940387


Cleaned Data set

In [ ]:
mean_total_amount = cleaned_taxi[:,13].mean()
print(mean_total_amount)

48.70217065868263
